# Generated by Django 5.0.1 on 2025-11-20 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AffiliateORM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("NIT", "Número de Identificación Tributaria"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "document_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Activo"), ("INACTIVE", "Inactivo")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Affiliate",
                "verbose_name_plural": "Affiliates",
                "db_table": "affiliates",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["document_number"], name="affiliates_documen_c2e13e_idx"
                    ),
                    models.Index(
                        fields=["status"], name="affiliates_status_fdfaaf_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="affiliates_created_9a546a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContributionORM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("contribution_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Efectivo"),
                            ("TRANSFER", "Transferencia"),
                            ("CARD", "Tarjeta"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="app_affiliate.affiliateorm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contribution",
                "verbose_name_plural": "Contributions",
                "db_table": "contributions",
                "ordering": ["-contribution_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["affiliate", "contribution_date"],
                        name="contributio_affilia_76576a_idx",
                    ),
                    models.Index(
                        fields=["contribution_date"],
                        name="contributio_contrib_1b6151_idx",
                    ),
                    models.Index(
                        fields=["verified"], name="contributio_verifie_d0591d_idx"
                    ),
                ],
            },
        ),
    ]
